# 《注意》
# 各端末ごとに環境に合わせて設定をして下さい。
# local.yamlは、rpa_seikyu.rb、rpa_rakuraku.rb、rpa_convpdf.rbと同じ階層のフォルダに入れてください。
# csv_path   : 楽楽販売から出力するCSVファイルのダウンロード先が固定となっているため、任意のパスを設定することはできません。
# rakurak pw : 楽楽販売のパスワードは定期的に変更になるため、変更した場合こちらの設定も変更して下さい。

# RPA機能
svr_cont: pro                               # dev:開発環境, pro:本番環境（社内開発サーバー）
csv_path: C:/Users/tanakak/Downloads        # CSVファイルのパス（ダウンロード先＋インポート元）
seikyu:
    id: admin                               # 請求システムにログインするID
    pw: admin                               # 請求システムにログインするパスワード
rakrak:
    id: tanakak                             # 楽楽販売にログインするID
    pw: ketukattin01+                       # 楽楽販売にログインするパスワード

# PDF出力機能
convpdf:
    path_pdf: D:/vagrant/rpa/pdf            # PDFファイルの出力先のパス
    path_exl: D:/vagrant/rpa/pdf            # Excelファイルの元ファイルのパス
